# Increase history limit
set-option -g history-limit 100000

# Use vi keys
setw -g mode-keys vi

# Window numbering
set -g base-index 1
set -g renumber-windows on

# Reduce escape delay
set -sg escape-time 1

# Split panes like vim
bind s split-window -v
bind v split-window -h

# Helps with OSC52
set -g allow-passthrough on

# Smart pane switching with vim awareness
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Mouse support
set -g mouse on

# Terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Clipboard / OSC52
set -s set-clipboard on

bind-key -Tcopy-mode-vi 'v' send -X begin-selection

# Resurrect / continuum
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Durable hide/show popup
set -g @popup-autostart on
set -gF @popup-id-format '#{b:pane_current_path}/{popup_name}'
bind h run "#{@popup-toggle} -Ed'##{pane_current_path}' -w90% -h90% --name=scratch"

# Status bar and catppuccin config
# Status bar position
set -g status-position top

# Status modules
set -g status-right-length 100
set -g status-left-length 100

set -g status-left "#{E:@catppuccin_status_session}"

set -g status-right "#{E:@catppuccin_status_user}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#[fg=#{@thm_mauve}]#[fg=#{@thm_crust},bg=#{@thm_mauve}]#{ram_icon} #[fg=#{@thm_fg},bg=#{@thm_surface_0}]#{ram_percentage}#[fg=#{@thm_surface_0},bg=default]"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_style "rounded"
# There is an issue with the current tab, the following lines fix it (source: https://github.com/catppuccin/tmux/issues/564)
set -g @catppuccin_window_current_left_separator "#{@catppuccin_window_left_separator}"
set -g @catppuccin_window_current_right_separator "#{@catppuccin_window_right_separator}"
